/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author Joan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**rootPaneCheckingEnabled
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        userLoginField = new javax.swing.JTextField();
        passwordLoginField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        userRegisterText = new javax.swing.JTextField();
        passwordRegisterText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(0, 153, 204));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        loginButton.setText("Ingresar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(14, 21, 11, 0);
        loginPanel.add(loginButton, gridBagConstraints);

        userLoginField.setForeground(new java.awt.Color(204, 204, 204));
        userLoginField.setText("Usuario");
        userLoginField.setToolTipText("");
        userLoginField.setPreferredSize(new java.awt.Dimension(100, 22));
        userLoginField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userLoginFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userLoginFieldFocusLost(evt);
            }
        });
        userLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginFieldActionPerformed(evt);
            }
        });
        userLoginField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userLoginFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 0);
        loginPanel.add(userLoginField, gridBagConstraints);

        passwordLoginField.setForeground(new java.awt.Color(204, 204, 204));
        passwordLoginField.setText("Contraseña");
        passwordLoginField.setPreferredSize(new java.awt.Dimension(100, 22));
        passwordLoginField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLoginFieldFocusLost(evt);
            }
        });
        passwordLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLoginFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        loginPanel.add(passwordLoginField, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/candado(1).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        loginPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mensaje.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        loginPanel.add(jLabel2, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11zon_cropped.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        loginPanel.add(jLabel5, gridBagConstraints);

        getContentPane().add(loginPanel, "card2");

        registerPanel.setLayout(new java.awt.GridBagLayout());

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        registerPanel.add(registerButton, gridBagConstraints);

        userRegisterText.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        registerPanel.add(userRegisterText, gridBagConstraints);

        passwordRegisterText.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        registerPanel.add(passwordRegisterText, gridBagConstraints);

        jLabel3.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        registerPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        registerPanel.add(jLabel4, gridBagConstraints);

        getContentPane().add(registerPanel, "card3");

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        this.dispose();
        
//        LoginDBController dbc = new LoginDBController();
//        User[] allUsers = dbc.getUsers();
//        User user = new User(userLoginField.getText(),passwordLoginField.getText());
//        //Time complexity goes brrr
//        for (User userLoop : allUsers) {
//            if (userLoop.getUserName().equals(user.getUserName()) && userLoop.getUserPassword().equals(user.getUserPassword())) {
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                    public void run() {
//                        new MainFrame().setVisible(true);
//                    }
//                });
//                this.dispose();
//            }
//        }


    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        //Most secure login ever
        LoginDBController controller = new LoginDBController();
        User user = new User(userRegisterText.getText(),passwordRegisterText.getText());
        controller.insertUser(user);
        loginPanel.setVisible(true);
        registerPanel.setVisible(false);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void userLoginFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userLoginFieldFocusGained
    if (userLoginField.getText().isEmpty()) {
    userLoginField.setText("Usuario");
    userLoginField.setForeground(Color.gray);
        
    }
    }//GEN-LAST:event_userLoginFieldFocusGained

    private void userLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginFieldActionPerformed
    passwordLoginField.requestFocus();
    }//GEN-LAST:event_userLoginFieldActionPerformed

    private void userLoginFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userLoginFieldFocusLost
if (userLoginField.getText().isEmpty()) {
    userLoginField.setText("Usuario");
    userLoginField.setForeground(Color.GRAY);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_userLoginFieldFocusLost

    private void passwordLoginFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFieldFocusGained
    if (passwordLoginField.getText().equals("Contraseña")) {
    passwordLoginField.setText("");
    passwordLoginField.setForeground(Color.black);     
    }
    }//GEN-LAST:event_passwordLoginFieldFocusGained

    private void passwordLoginFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFieldFocusLost
        if (passwordLoginField.getText().isEmpty()) {
    passwordLoginField.setText("Contraseña");
    passwordLoginField.setForeground(Color.GRAY);
}
    }//GEN-LAST:event_passwordLoginFieldFocusLost

    private void userLoginFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userLoginFieldKeyPressed
    if (userLoginField.getText().equals("Usuario")) {
    userLoginField.setText("");
    userLoginField.setForeground(Color.BLACK);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_userLoginFieldKeyPressed

    private void passwordLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLoginFieldActionPerformed
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        this.dispose();
        
//        LoginDBController dbc = new LoginDBController();
//        User[] allUsers = dbc.getUsers();
//        User user = new User(userLoginField.getText(),passwordLoginField.getText());
//        //Time complexity goes brrr
//        for (User userLoop : allUsers) {
//            if (userLoop.getUserName().equals(user.getUserName()) && userLoop.getUserPassword().equals(user.getUserPassword())) {
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                    public void run() {
//                        new MainFrame().setVisible(true);
//                    }
//                });
//                this.dispose();
//            }
//        }

    }//GEN-LAST:event_passwordLoginFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new LoginFrame().setVisible(true);
            }
        });
        
        //Why tf am i putting so much code in a fk frame
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField passwordLoginField;
    private javax.swing.JTextField passwordRegisterText;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField userLoginField;
    private javax.swing.JTextField userRegisterText;
    // End of variables declaration//GEN-END:variables
}
